# Generated by Django 4.2.2 on 2023-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(max_length=500),
        ),
    ]
